#ifndef _UI_PUBLIC_
#define _UI_PUBLIC_

#pragma once

#include "../engine/n_shared.h"

#define MENU_INDEX_TITLE    0
#define MENU_INDEX_MAIN     1
#define MENU_INDEX_LEVEL    2
#define MENU_INDEX_SETTINGS 3

typedef enum
{
    UI_CVAR_UPDATE,
    UI_CVAR_REGISTER,
    UI_CVAR_SET,
    UI_CVAR_VARIABLESTRINBUFFER,

    UI_MILLISECONDS,

    UI_PRINT,
    UI_ERROR,

    UI_RE_SETCOLOR,
    UI_RE_DRAWRECT,
    UI_RE_ADDENTITY,
    UI_RE_REGISTERSHADER,
    UI_RE_REGISTERTEXTURE,

    UI_SND_REGISTERSFX,
    UI_SND_PLAYSFX,
    UI_SND_STOPSFX,
    UI_SND_ADDLOOPINGSFX,
    UI_SND_CLEARLOOPINGSFX,
    UI_SND_PLAYTRACK,

    UI_ADDCOMMAND,
    UI_REMOVECOMMAND,
    UI_ARGC,
    UI_ARGV,
    UI_ARGS,

    UI_KEY_GETCATCHER,
    UI_KEY_SETCATCHER,
    UI_KEY_ISDOWN,
    UI_KEY_GETKEY,
    UI_MEMORY_REMAINING,

    UI_FS_FOPENWRITE,
    UI_FS_FOPENREAD,
    UI_FS_FILESEEK,
    UI_FS_FILETELL,
    UI_FS_FILELENGTH,
    UI_FS_WRITE,
    UI_FS_READ,
    UI_FS_WRITEFILE,
    UI_FS_FCLOSE,

    UI_FLOOR = 107,
    UI_CEIL,
    UI_ACOS,

    NUM_UI_IMPORT
} uiImport_t;

typedef enum
{
    UI_INIT,
    UI_KEY_EVENT,
    UI_SHUTDOWN,
    UI_CLEAR,
    UI_CONSOLE_COMMAND,
    UI_GETAPIVERSION,
    UI_FINISH_FRAME,

    NUM_UIEXPORT
} uiExport_t;

#endif