// ui_string_table.h -- all ui strings are stored here for a little bit of macro magic

UI_STRING(MENU_TITLE_ENTER_GAME)
UI_STRING(MENU_LOGO_STRING)
UI_STRING(MENU_MAIN_NEWGAME)
UI_STRING(MENU_MAIN_LOADGAME)
UI_STRING(MENU_MAIN_SETTINGS)
UI_STRING(MENU_MAIN_CREDITS)
UI_STRING(MENU_MAIN_EXIT_TO_TITLE)
UI_STRING(MENU_MAIN_EXIT_TO_DESKTOP)
