const char *fallbackShader_basic_vs =
"attribute vec3 a_Position;\n"
"attribute vec2 a_TexCoords;\n"
"attribute vec3 a_Color;\n"
"attribute vec3 a_Normal;\n"
"attribute float a_Alpha;\n"
"\n"
"varying vec3 v_Position;\n"
"varying vec2 v_TexCoords;\n"
"varying vec3 v_Color;\n"
"varying vec3 v_Normal;\n"
"varying float v_Alpha;\n"
"varying vec3 v_FragPos;\n"
"\n"
"uniform mat4 u_ModelViewProjection;\n"
"\n"
"void main()\n"
"{\n"
"    v_Position = a_Position;\n"
"    v_TexCoords = a_TexCoords;\n"
"    v_Color = a_Color;\n"
"    v_Normal = a_Normal;\n"
"    v_Alpha = v_Alpha;\n"
"\n"
"    gl_Position = u_ModelViewProjection * vec4(a_Position, 1.0);\n"
"}\n"
;
