
const char *fallbackShader_basic_vs =
"#version 330 core\n"
"layout(location = 0) in vec3 a_Position;\n"
"layout(location = 1) in vec2 a_TexCoords;\n"
//"in vec4 a_Normal;\n"
//"layout(location = 2) in vec4 a_Color;\n"
"\n"
"out vec3 v_Position;\n"
"out vec2 v_TexCoords;\n"
//"out vec4 v_Color;\n"
"out vec3 v_FragPos;\n"
"\n"
"uniform mat4 u_ModelViewProjection;\n"
"\n"
"void main()\n"
"{\n"
"    mat4 model = mat4(1.0);\n"
"\n"
"    v_Position = a_Position;\n"
"    v_TexCoords = a_TexCoords;\n"
//"    v_Color = a_Color;\n"
"\n"
"    v_FragPos = vec3(model * vec4(a_Position, 1.0));\n"
"\n"
"    gl_Position = u_ModelViewProjection * vec4(a_Position, 1.0);\n"
"}\n"
;

const char *fallbackShader_basic_fs =
"#version 330 core\n"
"out vec4 out_Color;\n"
"\n"
"in vec2 v_TexCoords;\n"
"in vec3 v_Position;\n"
//"in vec3 v_Color;\n"
"in float v_Alpha;\n"
"\n"
"uniform sampler2D u_DiffuseMap;\n"
"\n"
"void main()\n"
"{\n"
"   out_Color = vec4(1.0);\n"
//"    out_Color = texture(u_DiffuseMap, v_TexCoords);\n"
"}\n"
;
