typedef enum
{
	SPR_NULL = 0,

	//
	// player sprites
	//
	SPR_PLAYR_IDLE,
	SPR_PLAYR_MOVE0,
	SPR_PLAYR_MOVE1,
	SPR_PLAYR_MOVE2,
	SPR_PLAYR_STUNNED0,
    SPR_PLAYR_STUNNED1,
    SPR_PLAYR_STUNNED2,
	SPR_PLAYR_KNOCKBACK,
    SPR_PLAYR_GRAPPLE_PRIME0,
    SPR_PLAYR_GRAPPLE_PRIME1,
    SPR_PLAYR_GRAPPLE_SHOOT0,
    SPR_PLAYR_GRAPPLE_SHOOT1,
    SPR_PLAYR_GRAPPLE_SHOOT2,
    SPR_PLAYR_GRAPPLE_FLY,
    SPR_PLAYR_DESCEND0,
    SPR_PLAYR_DESCEND1,
    SPR_PLAYR_DESCEND2,
    SPR_PLAYR_SLIDE0,
    SPR_PLAYR_SLIDE1,
	
	NUMSPRITES
} spritenum_t;