#ifndef __SG_INFO__
#define __SG_INFO__

#pragma once

#define NUM_REVOLVER_SPRITES (SPR_MURSTAR_RLD1_L - SPR_PLAYR_PARRY6_HIT4_L)
#define NUM_PLASMA_SPRITES (SPR_PLASMA_FIRE_L - SPR_MURSTAR_RLD1_L)

// a lot of these are duplicates, that is until i add the sprites in
typedef enum
{
    SPR_PLAYR_IDLE_R,
    SPR_PLAYR_IDLE_L,
    SPR_PLAYR_PARRY0_R,
    SPR_PLAYR_PARRY0_L,
    SPR_PLAYR_PARRY1_R,
    SPR_PLAYR_PARRY1_L,
    SPR_PLAYR_PARRY2_HIT0_R,
    SPR_PLAYR_PARRY2_HIT0_L,
    SPR_PLAYR_PARRY3_HIT1_R,
    SPR_PLAYR_PARRY3_HIT1_L,
    SPR_PLAYR_PARRY4_HIT2_R,
    SPR_PLAYR_PARRY4_HIT2_L,
    SPR_PLAYR_PARRY5_HIT3_R,
    SPR_PLAYR_PARRY5_HIT3_L,
    SPR_PLAYR_PARRY6_HIT4_R,
    SPR_PLAYR_PARRY6_HIT4_L,
    SPR_MURSTAR_IDLE_R,
    SPR_MURSTAR_IDLE_L,
    SPR_MURSTAR_FIRE_R,
    SPR_MURSTAR_FIRE_L,
    SPR_MURSTAR_RLD0_R,
    SPR_MURSTAR_RLD0_L,
    SPR_MURSTAR_RLD1_R,
    SPR_MURSTAR_RLD1_L,
    SPR_PLASMA_IDLE_R,
    SPR_PLASMA_IDLE_L,
    SPR_PLASMA_FIRE_R,
    SPR_PLASMA_FIRE_L,
    SPR_PLAYR_DASH_R,
    SPR_PLAYR_DASH_L,
    SPR_PLAYR_MOVE0_R,
    SPR_PLAYR_MOVE0_L,
    SPR_PLAYR_MOVE1_R,
    SPR_PLAYR_MOVE1_L,
    SPR_PLAYR_MOVE2_R,
    SPR_PLAYR_MOVE2_L,
    SPR_PLAYR_MOVE3_R,
    SPR_PLAYR_MOVE3_L,
    SPR_PLAYR_DEAD,
    SPR_PLAYR_LEGS0_7_R,
    SPR_PLAYR_LEGS0_7_L,
    SPR_PLAYR_LEGS1_7_R,
    SPR_PLAYR_LEGS1_7_L,
    SPR_PLAYR_LEGS2_7_R,
    SPR_PLAYR_LEGS2_7_L,
    SPR_PLAYR_LEGS3_7_R,
    SPR_PLAYR_LEGS3_7_L,
    SPR_PLAYR_LEGS0_5_R,
    SPR_PLAYR_LEGS0_5_L,
    SPR_PLAYR_LEGS1_5_R,
    SPR_PLAYR_LEGS1_5_L,
    SPR_PLAYR_LEGS2_5_R,
    SPR_PLAYR_LEGS2_5_L,
    SPR_PLAYR_LEGS3_5_R,
    SPR_PLAYR_LEGS3_5_L,
    SPR_PLAYR_HB_IDLE_R,
    SPR_PLAYR_HB_IDLE_L,
    SPR_PLAYR_HB_STAB_R,
    SPR_PLAYR_HB_STAB_L,
    SPR_PLAYR_HB_SLASH_R,
    SPR_PLAYR_HB_SLASH_L,
    SPR_PLAYR_LEGS0_4_R,
    SPR_PLAYR_LEGS0_4_L,
    SPR_PLAYR_LEGS1_4_R,
    SPR_PLAYR_LEGS1_4_L,
    SPR_PLAYR_LEGS2_4_R,
    SPR_PLAYR_LEGS2_4_L,
    SPR_PLAYR_LEGS3_4_R,
    SPR_PLAYR_LEGS3_4_L,
    NUM_PLAYER_SPRITES,

    SPR_GRUNT_IDLE_R = 0,
    SPR_GRUNT_IDLE_L,
    NUM_GRUNT_SPRITES,

    NUMSPRITES = NUM_PLAYER_SPRITES
                + NUM_GRUNT_SPRITES
                + NUM_REVOLVER_SPRITES
                + NUM_PLASMA_SPRITES
} spritenum_t;

typedef enum
{
    S_NULL,

    S_PLAYR_IDLE,
    S_PLAYR_MOVE,
    S_PLAYR_DASH,
    S_PLAYR_MELEE,
    S_PLAYR_PARRY,

    S_MURSTAR_IDLE,
    S_MURSTAR_FIRE,
    S_MURSTAR_RLD,

    S_PLASMA_IDLE,
    S_PLASMA_FIRE,

    S_GRUNT_IDLE,
    S_GRUNT_MOVE,
    S_GRUNT_FIGHT,

    NUMSTATES
} statenum_t;

typedef struct {
    spritenum_t sprite;
    uint32_t frames;
    uint32_t tics;
    actionp_t action;
    statenum_t nextstate;
} state_t;

extern state_t stateinfo[NUMSTATES];

#endif
