code

equ trap_Print                              -1
equ trap_Error                              -2
equ trap_Key_IsDown                         -3
equ trap_Key_AnyDown                        -4
equ trap_Key_SetCatcher                     -5
equ trap_Key_GetCatcher                     -6
equ trap_Key_ClearStates                    -7
equ trap_Key_GetKey                         -8
equ G_CastRay                               -9
equ G_SetCameraData                         -10
equ G_LoadMap                               -11
equ G_SetBindNames                          -12
equ Sys_GetGPUConfig                        -13
equ Sys_GetClipboardData                    -14
equ trap_Milliseconds                       -15
equ trap_MemoryRemaining                    -16
equ trap_SnapVector                         -17
equ trap_SendConsoleCommand                 -18
equ trap_Args                               -19
equ trap_Argv                               -20
equ trap_Argc                               -21
equ trap_RemoveCommand                      -22
equ trap_AddCommand                         -23
equ Cvar_Register                           -24
equ Cvar_Update                             -25
equ Cvar_Set                                -26
equ Cvar_VariableStringBuffer               -27
equ trap_FS_GetFileList                     -28
equ trap_FS_FileLength                      -29
equ trap_FS_FOpenFileWrite                  -30
equ trap_FS_FOpenFileRead                   -31
equ trap_FS_FOpenWrite                      -32
equ trap_FS_FOpenRead                       -33
equ trap_FS_FOpenAppend                     -34
equ trap_FS_FOpenFile                       -35
equ trap_FS_FClose                          -36
equ trap_FS_Write                           -37
equ trap_FS_Read                            -38
equ trap_FS_WriteFile                       -39
equ trap_FS_FileSeek                        -40
equ trap_FS_FileTell                        -41
equ trap_FS_FOpenRW                         -42
equ trap_Snd_RegisterSfx                    -43
equ trap_Snd_RegisterTrack                  -44
equ trap_Snd_PlaySfx                        -45
equ trap_Snd_StopSfx                        -46
equ trap_Snd_QueueTrack                     -47
equ trap_Snd_SetLoopingTrack                -48
equ trap_Snd_ClearLoopingTrack              -49
equ RE_RenderScene                          -50
equ RE_ClearScene                           -51
equ RE_AddPolyToScene                       -52
equ RE_AddPolyListToScene                   -53
equ RE_AddEntityToScene                     -54
equ RE_AddLightToScene                      -55
equ RE_RegisterShader                       -56
equ RE_LoadWorldMap                         -57
equ G_LinkEntity                            -58
equ G_UnlinkEntity                          -59
equ G_SoundRecursive                        -60
equ trap_CheckWallHit                       -61
equ RE_RegisterSpriteSheet                  -62
equ RE_RegisterSprite                       -63
equ RE_AddSpriteToScene                     -64
equ G_SetActiveMap                          -65
equ trap_BeginSaveSection                   -66
equ trap_EndSaveSection                     -67
equ trap_SaveChar                           -68
equ trap_SaveInt                            -69
equ trap_SaveFloat                          -70
equ trap_SaveByte                           -71
equ trap_SaveUInt                           -72
equ trap_SaveString                         -73
equ trap_SaveVector2                        -74
equ trap_SaveVector3                        -75
equ trap_SaveVector4                        -76
equ trap_LoadChar                           -77
equ trap_LoadInt                            -78
equ trap_LoadFloat                          -79
equ trap_LoadByte                           -80
equ trap_LoadUInt                           -81
equ trap_LoadString                         -82
equ trap_LoadVector2                        -83
equ trap_LoadVector3                        -84
equ trap_LoadVector4                        -85
equ trap_GetSaveSection                     -86

equ ImGui_BeginWindow                       -401
equ ImGui_EndWindow                         -402
equ ImGui_IsWindowCollapsed                 -403
equ ImGui_SetWindowCollapsed                -404
equ ImGui_SetWindowPos                      -405
equ ImGui_SetWindowSize                     -406
equ ImGui_SetWindowFontScale                -407
equ ImGui_BeginMenu                         -408
equ ImGui_EndMenu                           -409
equ ImGui_MenuItem                          -410
equ ImGui_SetItemTooltipUnformatted         -411
equ ImGui_TextUnformatted                   -412
equ ImGui_TextMultiline                     -413
equ ImGui_TextWithHint                      -414
equ ImGui_InputFloat                        -415
equ ImGui_InputFloat2                       -416
equ ImGui_InputFloat3                       -417
equ ImGui_InputFloat4                       -418
equ ImGui_InputInt                          -419
equ ImGui_InputInt2                         -420
equ ImGui_InputInt3                         -421
equ ImGui_InputInt4                         -422
equ ImGui_SliderFloat                       -423
equ ImGui_SliderFloat2                      -424
equ ImGui_SliderFloat3                      -425
equ ImGui_SliderFloat4                      -426
equ ImGui_SliderInt                         -427
equ ImGui_SliderInt2                        -428
equ ImGui_SliderInt3                        -429
equ ImGui_SliderInt4                        -430
equ ImGui_ColorEdit3                        -431
equ ImGui_ColorEdit4                        -432
equ ImGui_ArrowButton                       -433
equ ImGui_Checkbox                          -434
equ ImGui_GetFontScale                      -435
equ ImGui_SetCursorPos                      -436
equ ImGui_SetCursorScreenPos                -437
equ ImGui_GetCursorPos                      -438
equ ImGui_GetCursorScreenPos                -439
equ ImGui_PushColor                         -440
equ ImGui_PopColor                          -441
equ ImGui_SameLine                          -442
equ ImGui_NewLine                           -443
equ ImGui_ColoredTextUnformatted            -444
equ ImGui_SeparatorText                     -445
equ ImGui_Separator                         -446
equ ImGui_ProgressBar                       -447
equ ImGui_OpenPopup                         -448
equ ImGui_CloseCurrentPopup                 -449
equ ImGui_BeginPopupModal                   -450
equ ImGui_EndPopup                          -451
equ ImGui_Button                            -452
equ ImGui_InputText                         -453
equ ImGui_InputTextMultiline                -454
equ ImGui_InputTextWithHint                 -455

equ memset                                  -901
equ memcpy                                  -902
equ memmove                                 -903
equ memchr                                  -904
equ strcpy                                  -905
equ strchr                                  -906
equ strstr                                  -907
equ strcmp                                  -908
equ strlen                                  -909
equ floor                                   -910
equ ceil                                    -911
equ acos                                    -912
equ sin                                     -913
equ cos                                     -914
equ atan2                                   -915
equ sqrt                                    -916
equ pow                                     -917
equ logf                                    -918
equ powf                                    -919
equ sqrtf                                   -920
equ strncpy                                 -921
equ strrchr                                 -922
