code

equ trap_Print                              -1
equ trap_Error                              -2
equ trap_Key_IsDown                         -3
equ trap_Key_AnyDown                        -4
equ trap_Key_SetCatcher                     -5
equ trap_Key_GetCatcher                     -6
equ trap_Key_ClearStates                    -7
equ trap_Key_GetKey                         -8
equ G_CastRay                               -9
equ G_SetCameraData                         -10
equ G_LoadMap                               -11
equ G_LinkEntity                            -12
equ G_UnlinkEntity                          -13
equ G_SoundRecursive                        -14
equ G_CheckWallHit                          -15
equ G_SetActiveMap                          -16
equ G_BeginSaveSection                      -17
equ G_EndSaveSection                        -18
equ G_SaveChar                              -19
equ G_SaveInt                               -20
equ G_SaveFloat                             -21
equ G_SaveByte                              -22
equ G_SaveUInt                              -23
equ G_SaveString                            -24
equ G_SaveVector2                           -25
equ G_SaveVector3                           -26
equ G_SaveVector4                           -27
equ G_LoadChar                              -28
equ G_LoadInt                               -29
equ G_LoadFloat                             -30
equ G_LoadByte                              -31
equ G_LoadUInt                              -32
equ G_LoadString                            -33
equ G_LoadVector2                           -34
equ G_LoadVector3                           -35
equ G_LoadVector4                           -36
equ G_GetSaveSection                        -37
equ Sys_GetGPUConfig                        -38
equ Sys_GetClipboardData                    -39
equ Sys_Milliseconds                        -40
equ Sys_MemoryRemaining                     -41
equ Sys_SnapVector                          -42
equ trap_SendConsoleCommand                 -43
equ trap_Args                               -44
equ trap_Argc                               -45
equ trap_Argv                               -46
equ trap_RemoveCommand                      -47
equ trap_AddCommand                         -48
equ Cvar_Register                           -49
equ Cvar_Update                             -50
equ Cvar_Set                                -51
equ Cvar_VariableStringBuffer               -52
equ trap_FS_GetFileList                     -53
equ trap_FS_FileLength                      -54
equ trap_FS_FOpenFileWrite                  -55
equ trap_FS_FOpenFileRead                   -56
equ trap_FS_FOpenWrite                      -57
equ trap_FS_FOpenRead                       -58
equ trap_FS_FOpenAppend                     -59
equ trap_FS_FOpenFile                       -60
equ trap_FS_FClose                          -61
equ trap_FS_Write                           -62
equ trap_FS_Read                            -63
equ trap_FS_WriteFile                       -64
equ trap_FS_FileSeek                        -65
equ trap_FS_FileTell                        -66
equ trap_FS_FOpenRW                         -67
equ Snd_RegisterSfx                         -68
equ Snd_RegisterTrack                       -69
equ Snd_PlaySfx                             -70
equ Snd_StopSfx                             -71
equ Snd_SetLoopingTrack                     -72
equ Snd_ClearLoopingTrack                   -73
equ RE_RenderScene                          -74
equ RE_ClearScene                           -75
equ RE_AddPolyToScene                       -76
equ RE_AddPolyListToScene                   -77
equ RE_AddEntityToScene                     -78
equ RE_AddLightToScene                      -79
equ RE_RegisterShader                       -80
equ RE_LoadWorldMap                         -81
equ RE_RegisterSpriteSheet                  -82
equ RE_RegisterSprite                       -83
equ RE_AddSpriteToScene                     -84
equ RE_DrawImage                            -85
equ RE_SetColor                             -86

equ ImGui_BeginWindow                       -401
equ ImGui_EndWindow                         -402
equ ImGui_IsWindowCollapsed                 -403
equ ImGui_SetWindowCollapsed                -404
equ ImGui_SetWindowPos                      -405
equ ImGui_SetWindowSize                     -406
equ ImGui_SetWindowFontScale                -407
equ ImGui_BeginMenu                         -408
equ ImGui_EndMenu                           -409
equ ImGui_MenuItem                          -410
equ ImGui_SetItemTooltipUnformatted         -411
equ ImGui_TextUnformatted                   -412
equ ImGui_TextMultiline                     -413
equ ImGui_TextWithHint                      -414
equ ImGui_InputFloat                        -415
equ ImGui_InputFloat2                       -416
equ ImGui_InputFloat3                       -417
equ ImGui_InputFloat4                       -418
equ ImGui_InputInt                          -419
equ ImGui_InputInt2                         -420
equ ImGui_InputInt3                         -421
equ ImGui_InputInt4                         -422
equ ImGui_SliderFloat                       -423
equ ImGui_SliderFloat2                      -424
equ ImGui_SliderFloat3                      -425
equ ImGui_SliderFloat4                      -426
equ ImGui_SliderInt                         -427
equ ImGui_SliderInt2                        -428
equ ImGui_SliderInt3                        -429
equ ImGui_SliderInt4                        -430
equ ImGui_ColorEdit3                        -431
equ ImGui_ColorEdit4                        -432
equ ImGui_ArrowButton                       -433
equ ImGui_Checkbox                          -434
equ ImGui_GetFontScale                      -435
equ ImGui_SetCursorPos                      -436
equ ImGui_SetCursorScreenPos                -437
equ ImGui_GetCursorPos                      -438
equ ImGui_GetCursorScreenPos                -439
equ ImGui_PushColor                         -440
equ ImGui_PopColor                          -441
equ ImGui_SameLine                          -442
equ ImGui_NewLine                           -443
equ ImGui_ColoredTextUnformatted            -444
equ ImGui_SeparatorText                     -445
equ ImGui_Separator                         -446
equ ImGui_ProgressBar                       -447
equ ImGui_OpenPopup                         -448
equ ImGui_CloseCurrentPopup                 -449
equ ImGui_BeginPopupModal                   -450
equ ImGui_EndPopup                          -451
equ ImGui_Button                            -452
equ ImGui_InputText                         -453
equ ImGui_InputTextMultiline                -454
equ ImGui_InputTextWithHint                 -455

equ memset                                  -901
equ memcpy                                  -902
equ memmove                                 -903
equ memchr                                  -904
equ strcpy                                  -905
equ strchr                                  -906
equ strstr                                  -907
equ strcmp                                  -908
equ strlen                                  -909
equ floor                                   -910
equ ceil                                    -911
equ acos                                    -912
equ sin                                     -913
equ cos                                     -914
equ atan2                                   -915
equ sqrt                                    -916
equ pow                                     -917
equ logf                                    -918
equ powf                                    -919
equ sqrtf                                   -920
equ strncpy                                 -921
equ strrchr                                 -922
