code

equ trap_Cvar_Update                    -1
equ trap_Cvar_Register                  -2
equ trap_Cvar_Set                       -3
equ trap_Cvar_VariableStringBuffer      -4
equ trap_Milliseconds                   -5
equ trap_Print                          -6
equ trap_Error                          -7
equ trap_RE_SetColor                    -8
equ trap_RE_DrawImage                   -9
equ trap_RE_AddPolyToScene              -10
equ trap_RE_AddPolyListToScene          -11
equ trap_RE_AddEntityToScene            -12
equ trap_RE_RegisterShader              -13
equ trap_RE_ClearScene                  -14
equ trap_RE_RenderScene                 -15
equ trap_Snd_RegisterSfx                -16
equ trap_Snd_PlaySfx                    -17
equ trap_Snd_StopSfx                    -18
equ trap_Snd_AddLoopingTrack            -19
equ trap_Snd_ClearLoopingTrack          -20
equ trap_Snd_PlayTrack                  -21
equ trap_AddCommand                     -22
equ trap_RemoveCommand                  -23
equ trap_Argc                           -24
equ trap_Argv                           -25
equ trap_Args                           -26
equ trap_Key_GetCatcher                 -27
equ trap_Key_SetCatcher                 -28
equ trap_Key_IsDown                     -29
equ trap_Key_GetKey                     -30
equ trap_Key_ClearStates                -31
equ trap_Key_AnyDown                    -32
equ trap_FS_FOpenWrite                  -33
equ trap_FS_FOpenRead                   -34
equ trap_FS_FileSeek                    -35
equ trap_FS_FileTell                    -36
equ trap_FS_FileLength                  -37
equ trap_FS_Write                       -38
equ trap_FS_Read                        -39
equ trap_FS_WriteFile                   -40
equ trap_FS_FClose                      -41
equ trap_GetGPUConfig                   -42
equ trap_GetClipboardData               -43
equ trap_Cmd_ExecuteText                -44
equ trap_MemoryRemaining                -45
equ ImGui_BeginWindow                   -46
equ ImGui_EndWindow                     -47
equ ImGui_IsWindowCollapsed             -48
equ ImGui_SetWindowCollapsed            -49
equ ImGui_SetWindowPos                  -50
equ ImGui_SetWindowSize                 -51
equ ImGui_SetWindowFontScale            -52
equ ImGui_BeginMenu                     -53
equ ImGui_EndMenu                       -54
equ ImGui_MenuItem                      -55
equ ImGui_SetItemTooltipUnformatted     -56
equ ImGui_InputText                     -57
equ ImGui_InputTextMultiline            -58
equ ImGui_InputTextWithHint             -59
equ ImGui_InputFloat                    -60
equ ImGui_InputFloat2                   -61
equ ImGui_InputFloat3                   -62
equ ImGui_InputFloat4                   -63
equ ImGui_InputInt                      -64
equ ImGui_InputInt2                     -65
equ ImGui_InputInt3                     -66
equ ImGui_InputInt4                     -67
equ ImGui_SliderFloat                   -68
equ ImGui_SliderFloat2                  -69
equ ImGui_SliderFloat3                  -70
equ ImGui_SliderFloat4                  -71
equ ImGui_SliderInt                     -72
equ ImGui_SliderInt2                    -73
equ ImGui_SliderInt3                    -74
equ ImGui_SliderInt4                    -75
equ ImGui_ColorEdit3                    -76
equ ImGui_ColorEdit4                    -77
equ ImGui_ArrowButton                   -78
equ ImGui_Checkbox                      -79
equ ImGui_GetFontScale                  -80
equ ImGui_SetCursorPos                  -81
equ ImGui_GetCursorPos                  -81
equ ImGui_SetCursorScreenPos            -82
equ ImGui_GetCursorScreenPos            -83
equ ImGui_PushColor                     -84
equ ImGui_PopColor                      -85
equ ImGui_SameLine                      -86
equ ImGui_NewLine                       -87
equ ImGui_Text                          -88
equ ImGui_ColoredText                   -89
equ ImGui_SeparatorText                 -90
equ ImGui_Separator                     -91
equ ImGui_ProgressBar                   -92
equ ImGui_BeginTable                    -93
equ ImGui_EndTable                      -94
equ ImGui_TableNextRow                  -95
equ ImGui_TableNextColumn               -96
equ G_LoadMap                           -97

equ memset                              -901
equ memcpy                              -902
equ strncpy                             -903
equ floor                               -904
equ acos                                -905
equ sin                                 -906
equ cos                                 -907
equ atan2                               -908
equ ceil                                -909
equ sqrt                                -910
equ pow                                 -911
equ logf                                -912
equ powf                                -913
equ sqrtf                               -914